live_config_reload = true

# alacritty-themes
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/3024.dark.toml"
]

[window]
opacity = 0.9

  [window.padding]
  x = 10
  y = 10

[font]
size = 10

    [font.bold]
    family = "FiraCode Nerd Font"
    style = "Bold"

    [font.bold_italic]
    family = "FiraCode Nerd Font"
    style = "Bold Italic"

    [font.italic]
    family = "FiraCode Nerd Font"
    style = "Italic"

    [font.normal]
    family = "FiraCode Nerd Font"
    style = "Regular"

# Spawn new instance in same directory
[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

# hints text or hyperlinks
[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }
