#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 10

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# MY SETTINGS #################################################################

#bspc config pointer_motion_interval 0

killall polybar
$HOME/.config/polybar/launch.sh

#BSPWM coloring
bspc config normal_border_color		"#000000"
bspc config active_border_color		"#000000"
bspc config focused_border_color	"#ff0000"
#bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

bspc config focus_follows_pointer true

flatpak run com.github.wwmm.pulseeffects --gapplication-service &

nvidia-settings --load-config-only --assign="SyncToVBlank=0" &

killall -q picom
picom &

killall -q volumeicon
volumeicon &

xsetroot -cursor_name left_ptr &
nitrogen --restore &
numlockx on &
lxpolkit &
psensor &
nm-applet &
polychromatic-tray-applet &



